apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jkopriva-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus@sha256:15b169ee450df443250178a63532e87fe9f8d6cab1a834c8ec2b6c9fb0f7b8c9
        name: my-java-quarkus
        resources: {}
status: {}
